---
date: "2022-03-20T17:39:21-07:00"
draft: false
title: Teaching
---

## University of Cambridge
**Undergraduates**: Seminar classes on the topics of **temporality** and **gender** for final-year history undergraduates. 

**Postgraduates**: Seminar classes and workshops on **research conceptualisation and presentation** for postgraduates.

## National University of Singapore
**Undergraduates**: Supervisions and tutorials on **writing and critical thinking**, **historical source criticism** for first-year undergraduates. Lectures and seminar discussions on **oral history methodology**.

## University of Hull
**Graduate interns**: bespoke training tailored to interns' self-identified learning and development goals, topics included: **digital graphics** (Inkscape, Adobe Illustrator, Canva), **digital storytelling and data visualizations** (Flourish, Datawrapper, MS Sway, Shorthand), **productivity tools** (MS Teams, MS Planner), **research tools and reference management** (Zotero, Endnote), **career development** (cover letters, job interviews).