---
date: "2022-03-20T17:39:21-07:00"
draft: false
title: Papers
---
## Peer Reviewed Publications

**MYM Wong**. (2021). A pause in time: history writers and the regicide of Charles I. *Historical Research* 94,  758-781. https://doi.org/10.1093/hisres/htab029 

**MYM Wong**. (2021). Using Correspondence and Manuscripts in Literary Archives. In *Research Methods for Primary Sources*, SAGE/Adam Matthew. https://doi.org/10.47594/rmps_0098  

**MYM Wong**. (2021). Using Newspapers as Historical Sources. In *Research Methods for Primary Sources*, SAGE/Adam Matthew. https://doi.org/10.47594/rmps_0105 

## Dissertation
**MYM Wong**. (2019). The impact of the regicide of Charles I on contemporary English notions of time and the future. University of Cambridge. https://doi.org/10.17863/CAM.46314


## Conference Papers


**MYM Wong**. (2019). Charles I’s execution and the destiny of monarchy in Britain and Europe. 
*Monarchy and Modernity since 1500*, University of Cambridge.

**MYM Wong**. (2018).News of the king’s execution: newsbooks, temporality, and the regicide of Charles I.
*8th Biennial Conference*, Society for Renaissance Studies.

**MYM Wong**. (2018). Reacting to Shock and Uncertainty: Some observations from the seventeenth century.
*Malaysia-Singapore Research Conference*, Cambridge.

**MYM Wong**. (2018). The Regicide of Charles I and Its Impact on Visions of Time and the Future.
*64th Annual Meeting*, Renaissance Society of America.

**MYM Wong**. (2018). Wielding the Future: historians and the execution of Charles I.
*Wolfson Research Event*, Wolfson College Cambridge.

**MYM Wong**. (2018). ‘A Prognostication for the Time Present and Future’: Astrologers, Time, and the Regicide of Charles I.
*Early Modern British and Irish History Seminar*, University of Cambridge.

**MYM Wong**. (2017). ‘What the world counts losse is gaine’: national trauma and historians’ conceptions of the future in early modern England.
*The Making of Humanities VI*, The Society for the History of the Humanities, Oxford.

**MYM Wong**. (2017). Coming to terms with disruption: the impact of the execution of Charles I on historians and their treatments of the past.
*Imitation and Innovation: Uses of the Past in the Medieval and Early Modern World*, Durham University.

**MYM Wong**. (2017).‘Inward horror will be their first tormentor’: the public execution of Charles I and its impact on historians and the future.
*Cruelty and Compassion: Postgraduate Conference*, University of Leeds.

**MYM Wong**. (2017).‘If tho doest not beware in time’: crisis and temporality in the almanacs of the English Civil Wars. *Rethinking Crisis*, The Oxford Research Centre in the Humanities (TORCH).

**MYM Wong**. (2017). ‘When the Bridegroome shall come’: Astrologers and time as rhetoric during the English Civil Wars.
*Revolution, Reformation and Re-formation*, Institute of Historical Research, University of London.

**MYM Wong**. (2016). Imagining Ice and Infinity: Constructions of Place in the Antarctic and Outer Space Treaties.
*Imagined Worlds in the History of Political Thought*,  University of London.

